### ISSUE TITLE
Fetching a certain file crashes the session

### ISSUE THREAD

**Issue by marcan** [hanwen/go-mtpfs#55] opened 2014-01-07 03:45 UTC
I'm trying to rsync out my storage with go-mtpfs, but it dies when it gets to a particular file. This is fully reproducible.

Log:
2014/01/07 03:36:55 Serialize: OPENDIR code: OK value: {Fh 3624094511791806 }
2014/01/07 03:36:55 Dispatch: READDIRPLUS, NodeId: 61220911621525770. data: {Fh 3624094511791806 off 0 sz 4096  L 0 NONBLOCK,DIRECTORY,0x8000} 
2014/01/07 03:36:55 Serialize: READDIRPLUS code: OK value:  2480 bytes data

2014/01/07 03:36:55 Dispatch: READDIRPLUS, NodeId: 61220911621525770. data: {Fh 3624094511791806 off 14 sz 4096  L 0 NONBLOCK,DIRECTORY,0x8000} 
2014/01/07 03:36:55 Serialize: READDIRPLUS code: OK value: 
2014/01/07 03:36:55 Dispatch: RELEASEDIR, NodeId: 61220911621525770. data: {Fh 3624094511791806 NONBLOCK,DIRECTORY,0x8000  L0} 
2014/01/07 03:36:55 Serialize: RELEASEDIR code: OK value: 
2014/01/07 03:36:55 Dispatch: LOOKUP, NodeId: 70472930737720. names: [.fdroid] 8 bytes
2014/01/07 03:36:55 Serialize: LOOKUP code: OK value: {1935244651517180 E1.000000000 A1.000000000 {M040755 SZ=0 L=0 1000:100 0*0 0:1935244651517180 A 0.000000000 M 0.000000000 C 0.000000000}}
2014/01/07 03:36:55 Dispatch: LOOKUP, NodeId: 1935244651517180. names: [icons] 6 bytes
2014/01/07 03:36:55 Serialize: LOOKUP code: OK value: {2744485209588160 E1.000000000 A1.000000000 {M040755 SZ=0 L=0 1000:100 0*0 0:2744485209588160 A 0.000000000 M 0.000000000 C 0.000000000}}
2014/01/07 03:36:55 Dispatch: LOOKUP, NodeId: 2744485209588160. names: [com.scottmain.android.searchlight.4.png] 40 bytes
2014/01/07 03:36:55 Serialize: LOOKUP code: OK value: {16571943440422084 E1.000000000 A1.000000000 {M0100644 SZ=2548 L=1 1000:100 0*0 0:16571943440422084 A 1369947675.000000000 M 1369947675.000000000 C 1369947675.000000000}}
2014/01/07 03:36:55 Dispatch: OPEN, NodeId: 16571943440422084. data: {O_RDONLY,0x8000} 
2014/01/07 03:36:55 Serialize: OPEN code: OK value: {Fh 3659278883880938 }
2014/01/07 03:36:55 Dispatch: READ, NodeId: 16571943440422084. data: {Fh 3659278883880938 off 0 sz 4096  L 0 RDONLY,0x8000} 
2014/01/07 03:36:55 MTP request ANDROID_GET_PARTIAL_OBJECT64 [13212 0 0 2548]
2014/01/07 03:36:55 MTP data 0xa00 bytes
2014/01/07 03:36:55 MTP bulk read 0x800 bytes.
2014/01/07 03:36:57 MTP response 0x0 []
2014/01/07 03:36:57 fatal error got type 0 (CONTAINER_UNDEFINED) in response, want CONTAINER_RESPONSE.; closing connection.
2014/01/07 03:36:57 MTP request CloseSession []

The file is 2548 bytes long:
-rw-rw-r-- root     sdcard_rw     2548 2013-05-30 21:01 com.scottmain.android.searchlight.4.png

**Comment by hanwen** [comment] 2015-05-10 19:41
probably fixed by https://github.com/hanwen/go-mtpfs/commit/d108c3d1a06449910bced6b027da926c41c6a2f1

**Closed by hanwen** 2015-05-10 19:42 UTC

**Comment by graue** [comment] 2015-05-11 02:31
Thanks, @hanwen! Sorry I never answered your question above... missed it somehow (I hadn't tried disabling Android extensions). Am super glad to hear that the issue is fixed. This will make syncing photos much more painless next time. :)

**Comment by ceylanb** [comment] 2019-01-17 07:20
I have the same problem. When I would like to open /DCIM/Camera folder in file system, the error is appeared.
